### ISSUE TITLE
The use of paramters produced by optimize TSS/PS feature

### ISSUE THREAD

**Issue by elhossary** [Sung-Huan/ANNOgesic#10]
The optimize TSS/PSS feature produces the best paramters for the next step of TSS/PS prediction. After the production of these paramters the user have to pass them manually to TSS/PS prediction function. In this way I have 2 issues:
1- Waiting optimization to finish and then passing the paramters manually, almost nobody wants to run the optimization without using the produced paramter in further steps
2- When working with multi-accession files such species that have plasmids or more than one chromosome. the optimization produce paramters set for each accession and when the user wants to pass the paramters, he will take only one of them to be passed to all of other accession.
it might seem minor thing for organisms with plasmid, but it's major for multi chromosome species such Vibrio Cholerae that has two simillar size chromosomes.
My sugesstion is:
The prediction tool looks automatically (or by a bool parameter) for optimized paramters and loads it if found. and then for each accession the tool should use the appropriate paramter set.

**Comment by Sung-Huan** [comment]
Thank you for the suggestions. Basically, running optimization for TSS/PS is an option not a necessary step. Some users (actually not few) do not want to spend time for producing benchmarking set (the users need to check the TSS/PS by hands for at least 200KB). Moreover, some users prefer more sensitive and some users prefer do not. Therefore, keeping the step of parameter optimization and the step of TSS/PS detection separated still a not bad choice. The users can choose which parameters that they want to use for the final detection (it may not be the default optimized one).
Regarding the parameter assignment for multi accessions, I think it is a good point that we can implement in the future. I will put it in the TODO list. For the current version, you can run the TSS/PS detection two times with two parameter sets for these two chromosomes, then merge them afterwards. Or you can split and store the two accessions to two files, then run them separately.

Best,

Sung-Huan

**Comment by elhossary** [comment]
Thank you for your reply, I agree that the two function should kept separate. I meant if the user ran the optimization most probably he will use the optimized parameters. Therefore I suggested the automatic loading of the optimized parameters via a boolean parameter in the prediction step. example: --auto_load_optimized_param.
Then it can be loaded up to the user choice. In this way, both tools are kept separate as well as the user have the option to run a complete pipeline without interruption for manual input.

**Comment by Sung-Huan** [comment]
Ah, OK, sounds good. It will be in TODO list as well.

**Comment by Sung-Huan** [comment]
The new version was released. The function of tss prediction was extended for using optimized parameters from "optimize_tss_ps" directly (--auto_load_optimized_parameters). Moreover, the users can also assign different parameters to multiple genomes individually (--genome_order, and with all the parameters of TSSpredator). For the details, please check the documentation.

**Comment by elhossary** [comment]
Thank you very much.
Have you upgraded the docker image?

**Comment by Sung-Huan** [comment]
Yes.

**Comment by elhossary** [comment]
Great, Thanks
