### ISSUE TITLE
Transcript detection

### ISSUE THREAD

**Issue by StephenLi55** [Sung-Huan/ANNOgesic#11]
Hi,

I have been trying to run transcript detection of my wiggle files using the following command:

annogesic transcript --project_path annogesic/ --annotation_files annogesic/input/references/annotation/11168_genome.gff3 --modify_transcript merge_overlap --frag_libs annogesic/input/wigs/fragment/iron_replete_limited_mRNA_3_forward.wig:frag:1:a:+ annogesic/input/wigs/fragment/iron_replete_limited_mRNA_3_reverse.wig:frag:1:a:- --replicate_frag 1_1
#==================================================
However, the following error message has been returned:

Parsing 11168_genome.gff3
Parsing iron_replete_limited_mRNA_3_forward.wig
Parsing iron_replete_limited_mRNA_3_reverse.wig
Merging wig files of 11168_genome.
Error: comparing input files of 11168_genome. failed. Please check the seq IDs of all gff and fasta files, they should be the same.
Please also check the wiggle files which should contain forward and reverse files.

#==================================================
As the seq IDs gff file and fasta files are the same (see the attached files), I am not sure what would have caused that error message. Is there any other issue in my command line?

best wishes,

Stephen 

[11168_genome.gff3.txt](https://github.com/Sung-Huan/ANNOgesic/files/4092603/11168_genome.gff3.txt)

[NCTC11168_genome.fasta.txt](https://github.com/Sung-Huan/ANNOgesic/files/4092606/NCTC11168_genome.fasta.txt)

**Comment by Sung-Huan** [comment]
Hi Stephen,

I think there are two issues:

1. I guess your wiggle files have different IDs. Could you please type "head annogesic/input/wigs/fragment/iron_replete_limited_mRNA_3_forward.wig" and paste what you get on the screen to me?
2. The format of your fasta and gff file is not good. It contains "|" which is pre-defined in Unix. Therefore, it will cause some errors. I know you probably get the files from public database. But, recently, these databases also gradually change their format. I would suggest you just used accession number as seq IDs to gff, fasta and wig files. Then, it should be fine. 
ex:
fasta file -
>**NC_002163.1**
AATATAA....
gff file-
**NC_002163.1**	EMBL	region	1	1641481	.	+	.	ID=NC_002163.1:1......
wig file-
track type=wiggle_0 name="Log_81116_R1_minus_TEX_in_NC_009839"
variableStep chrom=**NC_002163.1** span=1

From my side, I will add a small script to avoid this problem in the future.

Best,

Sung-Huan

**Comment by StephenLi55** [comment]
Hi Sung-Huan,

  Thanks for the quick response. I have changed all the chromosome name to NC_002163.1 and that has bypassed the issue. However, the following error message came out when I ran the same command line as last time: 
#=======================
Running transcript detection
Parsing 11168_genome.gff3
Parsing iron_replete_limited_mRNA_3_forward.wig
Parsing iron_replete_limited_mRNA_3_reverse.wig
Merging wig files of 11168_genome.
Importing fragment wig files
Computing transcripts for 11168_genome.
Error: The iron_replete_limited_mRNA_3_reverse.wig_folder can not be found in lib names!!!
Error: The iron_replete_limited_mRNA_3_reverse.wig_folder can not be found in lib names!!!
annogesic//output/transcripts/11168_genome._fragment
Merging gff files of 11168_genome.
Parsing 11168_genome._transcript.gff
Merging gff files of 11168_genome._transcript
Generating tables for the details
Error: The iron_replete_limited_mRNA_3_reverse.wig_folder can not be found in lib names!!!
Error: The iron_replete_limited_mRNA_3_reverse.wig_folder can not be found in lib names!!!
#=======================
Is that something to do with the way I store my library ? Both wig files are stored in  the folder annogesic/input/wigs/fragment/.

best wishes,

 Stephen

**Comment by Sung-Huan** [comment]
Could you paste the gff files and wiggle files to me? For wiggle file, I just needs the first two files.

**Comment by StephenLi55** [comment]
Sure.
Reruning the script after removing the "transcript" folder still lead to the same error messages.


All 4 files have been added with the .txt as they can't be uploaded here otherwise. I am only running those two wiggle files for now as a test run. 


[11168_genome.fa.txt](https://github.com/Sung-Huan/ANNOgesic/files/4097859/11168_genome.fa.txt)
[11168_genome.gff3.txt](https://github.com/Sung-Huan/ANNOgesic/files/4097861/11168_genome.gff3.txt)

[iron_replete_limited_mRNA_3_forward.wig.txt](https://github.com/Sung-Huan/ANNOgesic/files/4097863/iron_replete_limited_mRNA_3_forward.wig.txt)
[iron_replete_limited_mRNA_3_reverse.wig.txt](https://github.com/Sung-Huan/ANNOgesic/files/4097864/iron_replete_limited_mRNA_3_reverse.wig.txt)

**Comment by Sung-Huan** [comment]
OK, I think you deleted first line of wiggle file. You just need to restore it: 

track type=wiggle_0 name="iron_replete_limited_mRNA_3"

It should work, at least, it works well from my side. 
And I suggest you to remove the "3" in gff file (from gff3 to gff). It won't influence anything, just make the output filename looked better :)

**Comment by StephenLi55** [comment]
ahh thats awesome it is working now . Thanks =)

It generated an output file that looks like the following:

Genome  Name    Start   End     Strand  Detect_lib_type Associated_gene Associated_tss  Associated_term Avg_coverage:iron_replete_limited_mRNA_3/iron_replete_limited_mRNA_3
NC_002163.1     transcript_00000        772     794     +       fragment        NA      NA      NA      12.043478260869565
NC_002163.1     transcript_00001        2434    4841    +       fragment        NA      NA      NA      94.58803986710963
...

Are those NA expected? Or is there still some issue with my gff file?

**Comment by Sung-Huan** [comment]
Could you check which version of ANNOgesic that you use? From my side, I have the information of associated gene in the table.

**Comment by StephenLi55** [comment]
version 1.0.6. Shall I update it.

My command is as following:

annogesic transcript --project_path annogesic/ --annotation_files annogesic/input/references/annotation/11168_genome.gff --modify_transcript merge_overlap --frag_libs annogesic/input/wigs/fragment/iron_replete_limited_mRNA_3_forward.wig:frag:1:a:+ annogesic/input/wigs/fragment/iron_replete_limited_mRNA_3_reverse.wig:frag:1:a:- --replicate_frag 1_1

**Comment by Sung-Huan** [comment]
Hmm. The result is correct from my side by using the same command. Please try to update the version, it may solve the issue. If you can wait, I will upload a new version for fixing the old format issue that you meet before. You can also update to that version.

**Comment by Sung-Huan** [comment]
Ok, I uploaded a new version. Please update your ANNOgesic.

But, in general, the "associated_gene" shows the genes located in the transcript. If you did not need this information, the table is fine.

**Comment by StephenLi55** [comment]
Thanks ! 

The information of the "associated_gene" isnt too important at this stage. Was just worried that something has gone wrong. Good to know that the analysis has ran correctly.

**Comment by StephenLi55** [comment]
Hi,

  Just wondering what would be the best practise to run annogesic on a big number of a wig files (e.g. nearly 200). Would you suggest running them all together as the same library? Or to run them separately? Would that make a huge difference for the result?

  best wishes,

  Stephen

**Comment by Sung-Huan** [comment]
Hi,

With such huge libraries, I am not really sure how long of the running time and how big of the memory will take if you run them together...
Basically, you can run the predictions separately based on conditions (of course, the replicates of this condition should be included). Afterwards, you can check all the output tables or gff files together. This will only influence the results of statistics which is minor for the analysis. 

Best,

Sung-Huan

**Comment by StephenLi55** [comment]
Hi ,

  Thanks for the advice. I am now running the transcription detection and sRNA detection with conditions being separated. I realise the following warning message as I run sRNA detection:

Warninng: Repeat ID id-Cj1687 in gff file!!!
Warninng: Repeat ID id-Cj1687 in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!
Warninng: Repeat ID id-Cj1688c in gff file!!!

I presume that refer to some redundant annotation of my gff file (e.g. the CDs, the gene, the sequence features of the same gene). What effect would that have on the output? Shall I filter out those redundant information?

**Comment by Sung-Huan** [comment]
No, you don't need to worry about that. It is only warning message. In principle, ID should be unique. Therefore, I report this warning message to the users. But, it won't influence any detections. You don't need to change them. However, you need to remember that if you load the gff file containing repeat IDs to genome browser, it may only show one gene and the other repeat ones will be gone.

Best, 
Sung-Huan

**Comment by StephenLi55** [comment]
ah right good to know that. Thanks for the quick response.

thanks,

Stephen

**Comment by StephenLi55** [comment]
ah sorry to bother you again. The following error message appeared as I ran the sRNA detection:
Merging fasta files of 11168_genome
Running sRNA detection of 11168_genome
Merging data of sRNA
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/annogesic", line 2178, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/bin/annogesic", line 2094, in main
    args.func(controller)
  File "/home/linuxbrew/.linuxbrew/bin/annogesic", line 2137, in run_sRNA_detection
    controller.srna_detection()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/controller.py", line 632, in srna_detection
    srna.run_srna_detection(args_srna, log)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/srna.py", line 1026, in run_srna_detection
    prefixs = self._run_program(args_srna, log)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/srna.py", line 405, in _run_program
    os.path.join(args_srna.gffs, gff), tss, tex_datas)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/srna.py", line 422, in _merge_srna
    tss, args_srna)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/merge_sRNA.py", line 589, in merge_srna_table
    texs, out, tsss, args_srna)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/merge_sRNA.py", line 420, in compare_table
    cut = get_cutoff(srna, tsss, type_, tables, args_srna)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/merge_sRNA.py", line 348, in get_cutoff
    tss_type = tss.attributes["type"]
KeyError: 'type'

Am I right that it comes the an issue form my tss file? The file I used is attached here.

[11168_genome_tss.gff.txt](https://github.com/Sung-Huan/ANNOgesic/files/4180721/11168_genome_tss.gff.txt)

**Comment by Sung-Huan** [comment]
Yes, your tss file looks weird. For a proper gff format, ID is required (https://www.ensembl.org/info/website/upload/gff3.html). 

You can check my tutorial data, it contains simple information for attribute column in gff3 files. 
https://github.com/Sung-Huan/ANNOgesic/blob/master/tutorial_data/NC_009839_manual_TSS.gff

I would suggest you add ID and Name into the file.

Moreover, I guess you assign your TSS file by using "--tss_files 11168_genome_tss.gff". However, your tss file is not generated from ANNOgesic. If you just want to use this TSS file without running tss prediction in ANNOgesic. You should add "--tss_source" to your command as well. This function will classify the TSSs from the input TSS file for sRNA prediction.

**Comment by StephenLi55** [comment]
Hi,

  Thanks for those information. The TSS file has been fixed and it is running alright now.

  I am aware that some tss in my file are quite close to each other (within 10bp) or even in the same position, as they are taken from several separated study. Would that have a significant impact on the output? Or would it be better if I cluster the close ones together?

  best wishes,

  Stephen

**Comment by Sung-Huan** [comment]
Hi,

Good to hear that your issue is solved. Since you run TSS prediction separately, the positions of TSSs may be close or even the same. I would suggest to cluster the close ones together. Actually, If you run all the data by using tss prediction of ANNOgesic in one shot, ANNOgesic will also cluster the close ones. At the meanwhiles, I would also suggest you to keep the orginial files as backups. If you want to know some specific TSSs from which experiments, you still can get the information from these files.

Best,
Sung-Huan

**Comment by StephenLi55** [comment]
thanks . I am currently clustering those that are within 10bp. Would that be too close? 

My colleagues raised an issue about the possibility were some tss might be close together but are not clustered (e.g. those that are 12 bp), and that might lead to two overlaping sRNAs being predicted (even when it is in fact only one long sRNA). Am I right that annogesic would merge those overlaping sRNAs together?

and if I set "--filter_info tss", would that filter out any sRNAs that don't have a tss in its proximity? 

thanks =)

**Comment by Sung-Huan** [comment]
Actually, this is a very good question. For the default setting of ANNOgesic and TSSpredator, we use 3 bp as a cutoff to cluster TSSs. There is no golden standard. You have to decide it.

For the overlapping sRNAs, ANNOgesic will merge them as one sRNA. 

If you set  "--filter_info tss", ANNOgesic will use TSS as a filter to check all potential sRNAs. Based on the results, two folders will be generated. One is "all_candidates" and the other is "best_candidates". The sRNAs which pass the filter will be put in "best_candidates". And "all_candidates" will store all possible sRNAs with and without passing the filter. Therefore, you can check both of the files to select your target for further experiments.

**Comment by StephenLi55** [comment]
Thanks.

I see. If the sRNAs are going to be merged anyway, then having 10bp as the cutoff shouldn't make too much difference from having 3bp as a cutoff right?

Alright that all makes sense now. Glad that both files are retained. Thanks for clarifying the filtering.

**Comment by StephenLi55** [comment]
Hi,

  Can you explain how the replicates are handled? If only 1 out of my 3 replicates suggest certain region as a sRNA, would that be shown in the output file?  Or does the output only consists of predicted sRNA that are found in all 3 replicates ?

  best wishes,

  Stephen

**Comment by Sung-Huan** [comment]
Hi,

For more details, you can check the documentation of ANNOgesic subcommands (https://annogesic.readthedocs.io/en/latest/subcommands.html#srna-srna-detection)

Briefly say, there are three parameters for managing replicates in sRNA detection.

--tex_notex: If dRNA-Seq was used and TEX+/- libraries are assigned, a sRNA should be detected in both (TEX+ and TEX-, assigned by 2) or can be detected in only one library (TEX+ or TEX-, assigned by 1). Default is 2.
  
--replicate_tex: This value is the minimal number of replicates that a sRNA has to be detected in. The format is $NUMBERofCONDITION_$NUMBERofREPLICATE. If different --replicate_tex values need to be assigned to different conditions, please use spaces to separate them. For example, 1_2 2_2 3_3 means that  --replicate_tex is 2 in number 1 and number 2 conditions. In number 3 condition, --replicate_tex is 3. For assigning the same --replicate_tex to all conditions, use all_1 (--replicate_tex is 1 in all conditions).

Thus, for handling dRNA-Seq libs, these two parameters need to be both considered. For examples:

If --tex_notex 1 --replicate_tex all_2 was assigned, a sRNA is like:

exp1    rep1    tex+    detected
exp1    rep1    tex-     not detected
exp1    rep2    tex+    detected
exp1    rep2    tex-     detected

it will be included as a sRNA candidate. However, if --tex_notex 2 --replicate_tex all_2 was assigned, it will not be included because this sRNA can only be detected in tex+ lib in rep1. If we change to --tex_notex 2 --replicate_tex all_1, this sRNA will be restored to sRNA list because one replicate is enough.

--replicate_frag: Similar to --replicates_tex. This value is for libraries with fragmented transcripts or conventional RNA-Seq.

Therefore, if you want to include the sRNAs which can be detected in only one replicate, you can assign something like: --tex_notex 1 --replicate_tex all_1 or --replicate_frag all_1

If you want to make sRNA detection more strict, you can assign something like: --tex_notex 2 --replicate_tex all_3 or --replicate_frag all_3

Of course you can also assign different number based on different conditions like what I wrote above (something like --replicate_tex 1_2 2_2 3_3 --replicate_tex 1_1 2_1 3_1).

If you want to check the read counts for each library of a specific sRNA, you can check the output table in "tables" folder.

Best,

Sung-Huan

**Comment by StephenLi55** [comment]
Hi Sung-Huan,

  Thats great! . Thanks for the clear explanation.

  best wishes,

  Stephen

**Comment by StephenLi55** [comment]
Hi Sung-Huan,

  Apart from running sRNA detection on conventional RNA-seq data, I am whether I should also run sRNA detection on dRNA-seq data. 

  My impression so far is that dRNA-seq data can identify tss that helps defining the transcript boundary. However, my colleagues have already analysed those dRNA-seq data with other approaches and have generated a list of tss (which I have included in the sRNA detection for our conventional RNA-seq data). So I feel like running sRNA detection on those dRNA-seq data might be redundant, as their information are already incorporated in the sRNA detection from those conventional RNA-seq data.  

  Are there other benefit of running another round of sRNA detection on dRNA-seq data? 

  best wishes,

  Stephen

**Comment by Sung-Huan** [comment]
From my point of view, I would suggest to run dRNA-Seq data as well since you already have them. Actually, TEX- lib of dRNA-Seq can also be considered as a conventional RNA-Seq. It may happen that some sRNAs miss in the conventional RNA-Seq but can be detected in dRNA-Seq. Moreover, the output table of sRNA detection in ANNOgesic contains the information of the coverage values from input libs. Therefore, you always can check which libs support the sRNA candidates.

**Comment by StephenLi55** [comment]
Hi Sung-Huan,

  Thanks for the advice. sRNA detection has been ran on most of the RNA-seq amd dRNA-seq data, with the exception of a few due to errors.

  Detection from some fragmented libraries have prompted the following message:
Merging data of sRNA
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/annogesic", line 2178, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/bin/annogesic", line 2094, in main
    args.func(controller)
  File "/home/linuxbrew/.linuxbrew/bin/annogesic", line 2137, in run_sRNA_detection
    controller.srna_detection()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/controller.py", line 632, in srna_detection
    srna.run_srna_detection(args_srna, log)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/srna.py", line 1026, in run_srna_detection
    prefixs = self._run_program(args_srna, log)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/srna.py", line 405, in _run_program
    os.path.join(args_srna.gffs, gff), tss, tex_datas)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/srna.py", line 422, in _merge_srna
    tss, args_srna)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/merge_sRNA.py", line 584, in merge_srna_table
    texs, out, tsss, args_srna)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/merge_sRNA.py", line 413, in compare_table
    tss_pro, end_pro = get_tss_pro(type_, srna)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/annogesiclib/merge_sRNA.py", line 534, in get_tss_pro
    srna.attributes["start_cleavage"] != "NA"):
KeyError: 'start_cleavage'


  An example of my input command is as followed: 
annogesic srna --project_path annogesic/ --transcript_files annogesic/output/heat_transcripts/gffs/11168_genome_transcript.gff \
 --annotation_files annogesic/input/references/annotation/11168_genome.gff --fasta_files annogesic/input/references/fasta/11168_genome.fa \
 --filter_info tss sec_str --tss_files annogesic/input/manual_TSSs/11168_genome_tss.gff \
 --frag_libs \
 annogesic/input/wigs/fragment/red_heat_S6_forward.wig:frag:1:a:+ \
 annogesic/input/wigs/fragment/red_heat_S6_reverse.wig:frag:1:a:- \
 annogesic/input/wigs/fragment/green_heat_S7_forward.wig:frag:1:b:+ \
 annogesic/input/wigs/fragment/green_heat_S7_reverse.wig:frag:1:b:- \
 annogesic/input/wigs/fragment/black_heat_S5_forward.wig:frag:1:c:+ \
 annogesic/input/wigs/fragment/black_heat_S5_reverse.wig:frag:1:c:- \
 --replicate_frag all_1 --tss_source --detect_srna_in_cds \
 --compute_sec_structures --rnafold_path ../../../usr/local/bin/RNAfold --relplot_path ../../../usr/local/share/ViennaRNA/bin/relplot.pl \
 --mountain_path ../../../usr/local/share/ViennaRNA/bin/mountain.pl --mountain_plot --utr_derived_srna
 
#=======================================
Meanwhile, detection from the dRNA-seq data has promopted the following error message:

AttributeError: 'ArgsContainer' object has no attribute 'input_libs'

Example of the input command is as following: 
annogesic srna --project_path annogesic/ --transcript_files annogesic/output/Porcelli_transcripts/gffs/11168_genome_transcript.gff \
 --annotation_files annogesic/input/references/annotation/11168_genome.gff --fasta_files annogesic/input/references/fasta/11168_genome.fa \
 --filter_info tss sec_str --tss_files annogesic/input/manual_TSSs/11168_genome_tss.gff \
 --tex_notex_libs \
 annogesic/input/wigs/tex_notex/wildtype_notex_forward.wig:notex:1:a:+ \
 annogesic/input/wigs/tex_notex/wildtype_notex_reverse.wig:notex:1:a:- \
 annogesic/input/wigs/tex_notex/wildtype_tex_forward.wig:tex:1:a:+ \
 annogesic/input/wigs/tex_notex/wildtype_tex_reverse.wig:tex:1:a:- \
  --replicate_tex all_1 --tss_source --detect_srna_in_cds \
 --compute_sec_structures --rnafold_path ../../../usr/local/bin/RNAfold --relplot_path ../../../usr/local/share/ViennaRNA/bin/relplot.pl \
 --mountain_path ../../../usr/local/share/ViennaRNA/bin/mountain.pl --mountain_plot --utr_derived_srna

 mv annogesic/output/sRNAs/ annogesic/output/Porcelli_sRNA/
 #======================================================================
Are these errors caused by the script? Or is that something to do with my input?
Sorry for keep bothering you with various issues. Hopefully this is the last step.

thanks,

Stephen

**Comment by Sung-Huan** [comment]
They are looked like errors from the scripts. However, it is really difficult to check because I don't meet these errors by using my files. If you feel fine, please send these input files (wig files, fasta file, gff files of transcript, tss, genome annotation) to me (shyu@biochem.mpg.de), I can take a look.

**Comment by Sung-Huan** [comment]
Ah, the error may come from a argument --detect_srna_in_cds, that I should put in internal test and not be public. Please remove this argument and rerun it again. If the errors are still shown. I probably really need the input files to check.

**Comment by Sung-Huan** [comment]
The errors (including --detect_srna_in_cds) were fixed, and a new version was uploaded as well. Please use the latest version for your prediction.
