### ISSUE TITLE
Transcript command, Comparison step, division by zero error

### ISSUE THREAD

**Issue by IgnatiusPang** [Sung-Huan/ANNOgesic#15]
Dear ANNOgesic developer,

Thank you for releasing this useful tool. I have been running ANNOgesic (v 1.0.6) transcript command and it gave me the following error:

  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/stat_TA_comparison.py", line 335, in print_tag_stat
    str(float(express_gene) / float(stats["gene"]))))
ZeroDivisionError: float division by zero

The full log file are copied below. Would you please let me know what is the likely source of error (e.g. GFF file is not properly formatted etc...)? This way I can try a few changes. I was thinking it is a good idea to report this runtime error that is due to a division by zero, (e.g. it would be good to have more intuitive error messages to instruct the users on what went wrong). I think this is more of a suggestion rather than a bug. 

The tex and notex data is private, but the RNA-seq fragment data is public. Please let me know if you require the fragment files for debugging and if so the best way to send the files to you (I can send some sample .wig files and GFF file to you via a downloadable link.)

Yours sincerely,

Ignatius Pang

Running transcript detection
Parsing Sa_JKD6009_ratt.gff
Parsing ctrl_notex_pos.wig
Parsing ctrl_notex_neg.wig
Parsing ctrl_tex_pos.wig
Parsing ctrl_tex_neg.wig
Parsing vanco_notex_pos.wig
Parsing vanco_notex_neg.wig
Parsing vanco_tex_pos.wig
Parsing vanco_tex_neg.wig
Merging wig files of Sa_JKD6009_ratt
Parsing SRR568061_plus_strand.wig
Parsing SRR568061_minus_strand.wig
etc... etc... 
Parsing SRR568120_plus_strand.wig
Parsing SRR568120_minus_strand.wig
Merging wig files of Sa_JKD6009_ratt
Importing fragment wig files
Computing transcripts for Sa_JKD6009_ratt
/srv/scratch/z3371724/JKD6009_v1/output/transcripts/Sa_JKD6009_ratt_fragment
Importing tex_notex wig files
Computing transcripts for Sa_JKD6009_ratt
/srv/scratch/z3371724/JKD6009_v1/output/transcripts/Sa_JKD6009_ratt_tex_notex
Merging fragmented and tex treated ones
Merging gff files of Sa_JKD6009_ratt
Parsing Sa_JKD6009_ratt_transcript.gff
Parsing Sa_JKD6009_ratt_transcript.gfftmp
Merging gff files of Sa_JKD6009_ratt_transcript
Modifying Sa_JKD6009_ratt by refering to Sa_JKD6009_ratt.gff
Parsing Sa_JKD6009_ratt_transcript.gff
Parsing Sa_JKD6009_ratt.gff
Merging gff files of Sa_JKD6009_ratt
Comaring of transcripts and genome annotations
Traceback (most recent call last):
  File "/apps/python/3.7.3/bin/annogesic", line 2178, in <module>
    main()
  File "/apps/python/3.7.3/bin/annogesic", line 2094, in main
    args.func(controller)
  File "/apps/python/3.7.3/bin/annogesic", line 2131, in run_Transcript_Assembly
    controller.transcript()
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/controller.py", line 462, in transcript
    transcript.run_transcript(args_tran, log)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/transcript.py", line 332, in run_transcript
    self._compare_tss_cds(tas, args_tran, log)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/transcript.py", line 128, in _compare_tss_cds
    self._compare_cds(tas, args_tran, log)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/transcript.py", line 113, in _compare_cds
    args_tran.c_feature)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/stat_TA_comparison.py", line 405, in stat_ta_gff
    print_tag_stat(stats["All"], out_stat, express_gene, feature)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/stat_TA_comparison.py", line 335, in print_tag_stat
    str(float(express_gene) / float(stats["gene"]))))
ZeroDivisionError: float division by zero

**Comment by Sung-Huan** [comment]
Dear Ignatius,

I guess there is something wrong in your genome annotation gff file. Could you please provide Sa_JKD6009_ratt.gff to me?

Best
Sung-Huan

**Comment by Sung-Huan** [comment]
I reproduced your error from my side by assigning the non-existed genomic feature to --compare_feature_genome. I think it is also the error that you met. I updated a new version which can check the genomic features for transcript detection. Please update the version.

**Comment by IgnatiusPang** [comment]
Thank you very much Sung-Huan :) Yes, this fixed my problem! Your help is much appreciated.
