### ISSUE TITLE
UTR detection error, do not know how to resolve.

### ISSUE THREAD

**Issue by IgnatiusPang** [Sung-Huan/ANNOgesic#17]
Dear Sung-Huan,

I have tried to run the UTR function and got an error that I cannot resolve (please see the error message below). Would you please have a look at this for me? I have the input files but would prefer sending them to you in private over e-mail. Would you please let me know which e-mail address would be best to send files to you?

Yours Sincerely,

Ignatius

annogesic utr  --annotation_files Sa_JKD6009_ratt.gff  --transcript_files Sa_JKD6009_ratt_transcript.gff  --tss_files Sa_JKD6009_ratt_TSS.gff  --terminator_files jdk6009_gff_table_win8_sd4_cpm0_gw5.gff  --project_path JKD6009_v1

       ___    _   ___   ______                  _     
      /   |  / | / / | / / __ \____ ____  _____(_)____ \
  __ / /| | /  |/ /  |/ / / / / __ `/ _ \/ ___/ / ___/__\
 |  / ___ |/ /|  / /|  / /_/ / /_/ /  __(__  ) / /__    /
 | /_/  |_/_/ |_/_/ |_/\____/\__, /\___/____/_/\___/   /
 |                          /____/ 
 |__________________
 |_____________________
 |________________________________________________
 |                                                \
 |________________________________________________/

Running UTR detection
Checking gff file of Sa_JKD6009_ratt_TSS.gff
Checking gff file of Sa_JKD6009_ratt.gff
Checking gff file of Sa_JKD6009_ratt_transcript.gff
Checking gff file of jdk6009_gff_table_win8_sd4_cpm0_gw5.gff
Parsing Sa_JKD6009_ratt.gff
Parsing Sa_JKD6009_ratt_TSS.gff
Merging gff files of Sa_JKD6009_ratt_TSS
Parsing Sa_JKD6009_ratt_transcript.gff
Merging gff files of Sa_JKD6009_ratt_transcript
Parsing jdk6009_gff_table_win8_sd4_cpm0_gw5.gff
Merging gff files of Sa_JKD6009_ratt_term
Computing 5'UTRs of Sa_JKD6009_ratt
Traceback (most recent call last):
  File "/apps/python/3.7.3/bin/annogesic", line 2178, in <module>
    main()
  File "/apps/python/3.7.3/bin/annogesic", line 2094, in main
    args.func(controller)
  File "/apps/python/3.7.3/bin/annogesic", line 2134, in run_UTR_detection
    controller.utr_detection()
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/controller.py", line 481, in utr_detection
    utr.run_utr_detection(args_utr, log)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/utr.py", line 84, in run_utr_detection
    self._compute_utr(args_utr, log)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/utr.py", line 49, in _compute_utr
    "_".join([prefix, "5UTR.gff"])), args_utr)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/detect_utr.py", line 517, in detect_5utr
    args_utr.length)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/detect_utr.py", line 345, in get_5utr_from_other
    cdss, tss, cdss, length, False)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/detect_utr.py", line 326, in detect_feature_5utr
    locus_tag = fea.attributes["ID"]
KeyError: 'ID'

**Comment by IgnatiusPang** [comment]
The error was because of an extra new line at the end of some of the GFF files. Would you please include some check to avoid reading in that blank line? Thank you in advance.

**Comment by IgnatiusPang** [comment]
I'm trying to cut out a subset of the files (e.g. first 10%) of the genome, and send to you. When I re-run analysis with just the 10%, the UTR ran without fail. I am thinking there must be some specific lines within the GFFs files that causes the error. I will test further subsets soon... to be continued and will keep this updated.

**Comment by Sung-Huan** [comment]
If the error is due to the empty lines, Please remove that line and re-run ANNOgesic. I will also put some code for checking the gff file. If the error still occur, please let me know.

**Comment by Sung-Huan** [comment]
And also please make sure all lines in gff file should contain "ID" in the attributes. ID is required for gff file. If no "ID", please add unique ID by yourself.

**Comment by Sung-Huan** [comment]
And my email is shyu@biochem.mpg.de

**Comment by Sung-Huan** [comment]
I just test the empty line, it is not the issue. So, I think the problem is due to the "ID". You can send me the input files via, I will check it.

**Comment by IgnatiusPang** [comment]
I've now identified that in my input file, several lines do not have the 'ID' tag in the line. Once I  have added the ID, the input worked fine without error. Thank you for your help.

**Comment by Sung-Huan** [comment]
Great! I am also adding some new code for using position and strand to replace the ID information if ID is not available. When the code is ready, this error will not show anymore. Thank you for your input and testing.
