### ISSUE TITLE
Promoter detection ,problem with FASTA file 

### ISSUE THREAD

**Issue by IgnatiusPang** [Sung-Huan/ANNOgesic#18]
Dear Sung-Huan

I'm trying to get the promoter module to work, but I have got the following error shown below. I will send you the input files via e-mail. Would please help me in getting this to work?

Yours sincerely,

Igy

annogesic promoter \
 --tss_files  /tss_part_10.gff \
 --fasta_files Sa_JKD6009.fasta \
 --motif_width 45 2-10 \
 --parallels 10 \
 --project_path JKD6009_v1

      /   |  / | / / | / / __ \____ ____  _____(_)____ \
  __ / /| | /  |/ /  |/ / / / / __ `/ _ \/ ___/ / ___/__\
 |  / ___ |/ /|  / /|  / /_/ / /_/ /  __(__  ) / /__    /
 | /_/  |_/_/ |_/_/ |_/\____/\__, /\___/____/_/\___/   /
 |                          /____/ 
 |__________________
 |_____________________
 |________________________________________________
 |                                                \
 |________________________________________________/

Running promoter detection
Parsing Sa_JKD6009.fasta
Parsing tss_part_10.gff
Checking gff file of tss_part_10.gff
Merging gff files of Sa_JKD6009_TSS
Generating fasta file of Sa_JKD6009
Traceback (most recent call last):
  File "/apps/python/3.7.3/bin/annogesic", line 2178, in <module>
    main()
  File "/apps/python/3.7.3/bin/annogesic", line 2094, in main
    args.func(controller)
  File "/apps/python/3.7.3/bin/annogesic", line 2143, in run_MEME
    controller.meme()
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/controller.py", line 701, in meme
    meme.run_meme(args_pro, log)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/meme.py", line 397, in run_meme
    self._split_fasta_by_strain(input_path)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/annogesiclib/meme.py", line 198, in _split_fasta_by_strain
    "".join([filename[0], strain, filename[-1]])))
UnboundLocalError: local variable 'filename' referenced before assignment

**Comment by Sung-Huan** [comment]
I think I know the issue. It should be a simple mistake. Just send me the input files for double check.

**Comment by Sung-Huan** [comment]
OK, your case is quite special. The TSSs are all orphan ones. Therefore, it cause the error. I will fix it and update a new version tomorrow.

**Comment by Sung-Huan** [comment]
Perhaps our server just upgraded, the run is finished faster than I thought. The error of ANNOgesic was fixed and your data was successfully analyzed without any errors from our side. Please update your ANNOgesic to latest version (1.0.14).

**Comment by IgnatiusPang** [comment]
Thank you for the fix. I used TSS predator with default settings to get the TSS, and I provided a GFF gene annotation file. Would you have any idea why they will all be orphans (e.g. some parameters I have missed in TSS Predator). I think the error occurs there at the TSS predator step in the first place (which trickled down to the Promoter step). Ideally, I must fix it in the TSS Predator step. Would you please give me some ideas of what to fix on my end in running TSS predator?

**Comment by IgnatiusPang** [comment]
I think what we will do is to run TSS predator with another version of the GFF annotation file and hope this file will be a lot cleaner and help fix the issues with Orphans. I will close this thread now. Thank you very much.
