### ISSUE TITLE
Multiple data set

### ISSUE THREAD

**Issue by Rexomania1** [Sung-Huan/ANNOgesic#19]
Hello Sung-Huan,

I have multiple datasets (4, thus 8 TEX treated files) of the same bacteria tested under different conditions. I am interested in identifying the expression of sRNAs under these different conditions. Can I use Annogesic to run all the datasets at once or do you I have to run them separately, thus is Annogesic able to provide separate output files for each dataset in on run? Or do I have to run them each data individually?

**Comment by Sung-Huan** [comment]
Hi,

If the dataset is from the same bacteria, you can run it at once. ANNOgesic will compare the dataset for checking the overlapping regions. If you want to see which sRNAs are expressed in the specific conditions, the output table includes all required information, such as the columns called Avg_coverage:$LIB_NAME in tht output table.

**Comment by Rexomania1** [comment]
Thank you for your response.
