### ISSUE TITLE
too many warnings in target prediction

### ISSUE THREAD

**Issue by elhossary** [Sung-Huan/ANNOgesic#20]
In the latest version in srna_target, I get thousands of a warnings like that:

WARNING: File ' ANNOgesic_analysis/output/sRNA_targets/RNAplex_results/NC_018660.1/RNAplfold/3_O3K_RS26175_cds-WP_000869859.1_11934-12962_-_openen ' open error                               
WARNING: File ' ANNOgesic_analysis/output/sRNA_targets/RNAplex_results/NC_018660.1/RNAplfold/3_O3K_RS26170_cds-WP_001387337.1_11391-11930_-_openen ' open error                               
WARNING: File ' ANNOgesic_analysis/output/sRNA_targets/RNAplex_results/NC_018660.1/RNAplfold/3_O3K_RS26165_cds-WP_000019440.1-2_9596-10576_-_openen ' open error                              
WARNING: File ' ANNOgesic_analysis/output/sRNA_targets/RNAplex_results/NC_018660.1/RNAplfold/3_O3K_RS26125_cds-WP_001189111.1_3211-4719_-_openen ' open error                                 
WARNING: File ' ANNOgesic_analysis/output/sRNA_targets/RNAplex_results/NC_018660.1/RNAplfold/3_O3K_RS26110_cds-WP_014971748.1_757-1737_-_openen ' open error     

is there is any explanation why is this happening

**Comment by Sung-Huan** [comment]
Your feature ID is really really long, ex: 3_O3K_RS26175_cds-WP_000869859.1. It is over the limitation that RNAplfold can handle. If you can try to rename the ID, the issue should be able to solved. If you want to wait, I can try to find some time to add some code for the renaming.

**Comment by elhossary** [comment]
Thanks Sung-Huan for the quick response,
is it fixed in this commit?
https://github.com/Sung-Huan/ANNOgesic/commit/7a974bcfadbb973bb64b34b389a120deee91d4f6#diff-72b8a4e1f52794bcfc6a3fb9abfac979

If yes, Is the docker image ready?

**Comment by Sung-Huan** [comment]
I am testing it. If everything goes well, I will update it tomorrow.

**Comment by elhossary** [comment]
Okay thanks

**Comment by Sung-Huan** [comment]
ANNOgesic is updated. Now the long id should be handled properly.

**Comment by elhossary** [comment]
Works, thanks
