### ISSUE TITLE
sRNA prediction error

### ISSUE THREAD

**Issue by Rexomania1** [Sung-Huan/ANNOgesic#21]
Hi Sung-Huan,
I am running sRNA prediction on a bacteria with 3 plasmids. Unfortunately I got the attached error. Hopefully you can be able to help me. 
Secondly, I want to enquire if it is necessary to list all the  --promoter_names (MOTIF_1 etc) if one wants to identify all possible sRNAs or it can be left out as default (none)?

Building a new DB, current time: 07/23/2020 17:45:00
New DB name:   /Rex/uli/eco83/annogesic/input/databases/sRNA_database_BSRD
New DB title:  /Rex/uli/eco83/annogesic/input/databases/sRNA_database_BSRD.fa
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /Rex/uli/eco83/annogesic/input/databases/sRNA_database_BSRD
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 897 sequences in 0.025398 seconds.
Running Blast of GCF_000299455.1_ASM29945v1_genomic in /Rex/uli/eco83/annogesic/input/databases/sRNA_database_BSRD
Warning: [blastn] Query is Empty!
Generating table for GCF_000299455.1_ASM29945v1_genomic
Classifying sRNA of GCF_000299455.1_ASM29945v1_genomic
Traceback (most recent call last):
  File "/usr/local/bin/annogesic", line 2230, in <module>
    main()
  File "/usr/local/bin/annogesic", line 2146, in main
    args.func(controller)
  File "/usr/local/bin/annogesic", line 2189, in run_sRNA_detection
    controller.srna_detection()
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/controller.py", line 641, in srna_detection
    srna.run_srna_detection(args_srna, log)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/srna.py", line 1039, in run_srna_detection
    self._class_srna(prefixs, args_srna, log)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/srna.py", line 773, in _class_srna
    classify_srna(os.path.join(self.all_best["all_gff"],
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/sRNA_class.py", line 286, in classify_srna
    class_num, index = print_stat_title(
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/sRNA_class.py", line 170, in print_stat_title
    "2d_energy", srna_datas[strain][0].attributes.keys(),
IndexError: list index out of range

Thanks

**Comment by Sung-Huan** [comment]
Sorry, the information is too few to know what happen. Could you please send me via email including your input files and also the command that you gave. I will take a look.

Regarding the promoter, it is not necessary. You can skip it. The promoter information if for ranking of the sRNAs. It is kind of fine-tune. Thus, the list of sRNAs won't be changed, but the ranking may have slightly different or keep the same.

**Comment by Sung-Huan** [comment]
btw, did you run ANNOgesic via docker or you install standalone version by yourself? If you did not use docker, which version of blast+ did you use for this run?

**Comment by Rexomania1** [comment]
I did run ANNOgesic via docker....I will send you my input files via email soon.

**Comment by Rexomania1** [comment]
email sent :)

**Comment by Rexomania1** [comment]
Hi Sung-Huan, I got another error from running sRNA prediction....hopefully you can have a look and clarify for me. Thanks 

command: annogesic srna -pj $Annogesic -d tss blast_srna sec_str blast_nr -g $Annogesic/input/references/annotations/*.gff -t $Annogesic/output/TSSs/gffs/*.gff -p $Annogesic/output/processing_sites/gffs/*_processing.gff -a $Annogesic/output/transcripts/gffs/*_transcript.gff -f $Annogesic/input/references/fasta_files/*.fa -e $Annogesic/output/terminators/gffs/best_candidates/*_term.gff -pt $Annogesic/output/promoters/$NAME/MEME/*$NAME_NC_018658.1_all_types_50_nt/meme.csv $Annogesic/output/promoters/$NAME/MEME/*$NAME_NC_018659.1_all_types_50_nt/meme.csv $Annogesic/output/promoters/$NAME/MEME/*$NAME_NC_018660.1_all_types_50_nt/meme.csv $Annogesic/output/promoters/$NAME/MEME/*$NAME_NC_018666.1_all_types_50_nt/meme.csv -m -u -cs -sf -nf -nd $nrdatabase -sd $srnadatabase -tl $TEX_LIBS -rt all_1

Error: 
Building a new DB, current time: 07/24/2020 21:57:21
New DB name:   /Rex/uli/eco83/annogesic/input/databases/sRNA_database_BSRD
New DB title:  /Rex/uli/eco83/annogesic/input/databases/sRNA_database_BSRD.fa
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /Rex/uli/eco83/annogesic/input/databases/sRNA_database_BSRD
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 897 sequences in 0.022815 seconds.
Running Blast of GCF_000299455.1_ASM29945v1_genomic in /Rex/uli/eco83/annogesic/input/databases/sRNA_database_BSRD
Warning: [blastn] Query is Empty!
Traceback (most recent call last):
  File "/usr/local/bin/annogesic", line 2230, in <module>
    main()
  File "/usr/local/bin/annogesic", line 2146, in main
    args.func(controller)
  File "/usr/local/bin/annogesic", line 2189, in run_sRNA_detection
    controller.srna_detection()
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/controller.py", line 641, in srna_detection
    srna.run_srna_detection(args_srna, log)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/srna.py", line 1036, in run_srna_detection
    self._compare_term_promoter("_".join([self.prefixs["merge_table"],
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/srna.py", line 958, in _compare_term_promoter
    compare_srna_promoter(os.path.join(self.all_best["all_gff"],
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/compare_srna_promoter.py", line 47, in compare_srna_promoter
    srnas, pros = read_file(srna_gff, args_srna)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/compare_srna_promoter.py", line 21, in read_file
    row[3] in args_srna.promoter_name):
TypeError: argument of type 'NoneType' is not iterable

**Comment by Sung-Huan** [comment]
I tested your data with exactly the same command that you gave. I got no error. Everything went through successfully. Could you please check which version are you using?

**Comment by Sung-Huan** [comment]
And for your last error, I think it is due to no promoter name assigned. You should add -pn MOTIF1 .... something like this.

**Comment by Rexomania1** [comment]
I am using ANNOgesic version 1.0.11
I want to identify every possible sRNA, therefore should I list all the promoter MOTIFs? eg. -pn MOTIF1,......MOTIF7?

**Comment by Sung-Huan** [comment]
I would suggest:

1. update your ANNOgesic to the latest version. Since I can finish the run in Docker container, you should be able to make it as well.
2. It depends on you. But I checked your promoter table, they only have MOTIF1-3, not sure how did you get MOTIG4-7. Like what I said before, the motif information is used for ranking the sRNAs. No matter how many motifs that you assigned or even no motif information, all sRNA candidates will still be detected. So, the number of sRNAs will not be changed by promoter information. Only the ranking will be slightly different.

**Comment by Sung-Huan** [comment]
And in addition, I personally do not like to use wildcard for running the script - like *.gff. If you have more than one gff file in the same folder, all of the files will be used for the run. If a file which is not related to your data or there are some intermediate files generated, it will cause errors. So, I would also suggest that put the full filenames to the arguments.

**Comment by Sung-Huan** [comment]
This is the command that I use for my run. Actually, it is the same as yours. I just replace the wildcare to the full names.

    annogesic \
        srna \
        -d tss blast_srna sec_str blast_nr \
        -g $Annogesic/input/references/annotations/GCF_000299455.1_ASM29945v1_genomic.gff \
        -t $Annogesic/output/TSSs/gffs/GCF_000299455.1_ASM29945v1_genomic_TSS.gff \
        -a $Annogesic/output/transcripts/gffs/GCF_000299455.1_ASM29945v1_genomic_transcript.gff \
        -f $Annogesic/input/references/fasta_files/GCF_000299455.1_ASM29945v1_genomic.fa \
        --processing_site_files ANNOgesic_r/output/processing_sites/gffs/GCF_000299455.1_ASM29945v1_genomic_processing.gff \
        --terminator_files ANNOgesic_r/output/terminators/gffs/GCF_000299455.1_ASM29945v1_genomic_term.gff \
        -u \
        -pt huan/promoter_motifs_GCF_000299455.1_ASM29945v1_genomic_NC_018658.1_all_types_50_nt/meme.csv huan/promoter_motifs_GCF_000299455.1_ASM29945v1_genomic_NC_018659.1_all_types_50_nt/meme.csv huan/promoter_motifs_GCF_000299455.1_ASM29945v1_genomic_NC_018660.1_all_types_50_nt/meme.csv huan/promoter_motifs_GCF_000299455.1_ASM29945v1_genomic_NC_018666.1_all_types_50_nt/meme.csv \
        -cs \
        -m \
        --srna_format \
        --srna_database_path ANNOgesic/input/databases/sRNA_database_BSRD \
        --nr_format \
        --nr_database_path ANNOgesic/input/databases/nr \
        -tl $tex_notex_libs \
        -pn MOTIF_1 MOTIF_2 MOTIF_3 \
        -rt all_1 \
        -pj $Annogesic

**Comment by Rexomania1** [comment]
I am running other parallel analysis that have up to MOTIF7.......however thanks for your response. I try to update the version of ANNOgesic to continue the run. Thank you.

**Comment by Sung-Huan** [comment]
OK, if you still have the same issue in lastest version, please do not delete any files and just pack all the files in $ANNOgesic/output/sRNAs to me. Then I can directly check the intermediate files.

**Comment by Rexomania1** [comment]
Alright, I will do so if the issues come up again.
