### ISSUE TITLE
Predicted sRNAs seem too long

### ISSUE THREAD

**Issue by StephenLi55** [Sung-Huan/ANNOgesic#23]
Hi Sung-Huan,

  I have previous predicted a list of sRNAs in Campylobacter genome using ANNOgesic. To evaluate the quality of the prediction, I compared the prediction with previously annotated sRNAs. While the predictions successfully detect most annoatated sRNAs, I am alarmed that the predicted sRNA appeared too long.

In the attached screenshot below, my prediction (Li_ANNOgesic_154) successfully detected the annotated ncRNA rnpB, the prediction is over double the length of the annotated ncRNA, with the 3'end particularly far off from where the read coverage drop off (I presume ANNOgesic has included some background noise after the annotated 3'end into the prediction). Similarly pattern has been observed in almost all of the predictions.

While it is possible to refine the predictions by mannually adjusting the cutoff threshold, that will be tricky in my case as I am working with nearly 100 set of RNA-Seq data, and each dataset would have different level of background noise. Are there any other parameters in ANNOgesic that can be adjusted to improve the sRNA boundary prediction?

![case1](https://user-images.githubusercontent.com/52718314/110314283-8e8e2380-7fff-11eb-8714-883f163eb60c.png)

best wishes,

Stephen

**Comment by Sung-Huan** [comment]
Dear Stephen,

Different library has different deep. If you want to shorten your sRNA length, you should change the parameters for transcript detection, not sRNA detection. sRNA detection is based on the list of transcripts. Thus, if the transcript does not overlap the known genes and the length of transcript is within proper sRNA range, it will be assigned as sRNA candidates.  Li_ANNOgesic_154 looks like a long transcript, but includes a lot of relative low coverage values. Probably, you have deep libraries, so the coverage values of the low expression region may higher than 10. You can raise up the cutoff of coverage for transcript detection ("--height" for subcommand "transcript", default is 10). You can also change "--tolerance" if you feel the transcripts become too fragmental.

Best,
Sung-Huan
