### ISSUE TITLE
 Merging results srna_target, wrong column names

### ISSUE THREAD

**Issue by gprezza** [Sung-Huan/ANNOgesic#24]
Hi!

I think I found a small bug when merging results from different methods of srna_target:

https://github.com/Sung-Huan/ANNOgesic/blob/7b136ae125eef47a2e9e16b4ca90f5766ecb0570/annogesiclib/merge_rnaplex_rnaup.py#L462
https://github.com/Sung-Huan/ANNOgesic/blob/7b136ae125eef47a2e9e16b4ca90f5766ecb0570/annogesiclib/merge_rnaplex_rnaup.py#L463

I guess these two lines should instead be:
```
 "Energy_" + methods[0], "Rank_" + methods[0], 
 "Energy_" + methods[1], "Rank_" + methods[1]]) + "\n") 
```
(please note the indexes of methods)

**Comment by Sung-Huan** [comment]
Thank you for your information. Yes, it is a bug. I will find time to fix it.

**Comment by Sung-Huan** [comment]
The bug was fixed in the latest version.
