### ISSUE TITLE
Path to instal sgemehl in get_package_database.sh is old

### ISSUE THREAD

**Issue by g1o** [Sung-Huan/ANNOgesic#26]
Path to instal sgemehl in get_package_database.sh is old
## currently : 
VERSION=0_2_0
wget -cP $TOOL_PATH http://www.bioinf.uni-leipzig.de/Software/segemehl/segemehl_${VERSION}.tar.gz
## should be if keeping the v_0_2_0 : 
wget -cP $TOOL_PATH http://www.bioinf.uni-leipzig.de/Software/segemehl/old/segemehl_${VERSION}.tar.gz

## or try newer version:
    VERSION=0.3.4
    wget -cP $TOOL_PATH http://www.bioinf.uni-leipzig.de/Software/segemehl/downloads/segemehl-${VERSION}.tar.gz
    cd $TOOL_PATH
    tar -zxvf segemehl-${VERSION}.tar.gz
    cd segemehl-${VERSION}/
    make all
    cd $TOOL_PATH
    rm segemehl-${VERSION}.tar.gz

**Comment by Sung-Huan** [comment]
Hi,

Thank you for your information. We will change it.

Btw, the interfaces of some tools were changed. We are working on modifying the code for adapting these new versions of tools like segemehl and TSSpredator. If you meet the issue of versions, please use Docker image for the time being. We will update the code as soon as possible.

Best,
Sung-Huan
