### ISSUE TITLE
Conda recipe?

### ISSUE THREAD

**Issue by apredeus** [Sung-Huan/ANNOgesic#3]
Hello Sung-Huan, 

I've had quite a few problems installing the program on the cluster, where I don't have root privileges. There's a bioconda version of singularity, which I installed successfully, but when I tried to run the image, it generates the following error: 

> ERROR  : Failed invoking the NEWUSER namespace runtime: Invalid argument
> ABORT  : Retval = 255

I've installed singularity and built annogesic image on my local workstation, and that worked all right. 

I think you should consider making a bioconda recipe (once you already went through the trouble of making a docker container), that would really help people install and use it. 

Thank you for the software!

**Comment by Sung-Huan** [comment]
Dear Alex,

Thank you for your suggestion. We have thought about building a  
bioconda version before. However, there are too many third party tools  
which are not in bioconda currently. Thus, we decide to use Docker and  
Singularity. We will consider and try to build a conda recipe. Now,  
the best solution for you is asking your administrator to install  
Singularity with root. It is also beneficial for all the users if they  
want to install tools via Singularity.

Best regards,

Sung-Huan


Quoting Alex Predeus <notifications@github.com>:

**Comment by apredeus** [comment]
Thank you.
