### ISSUE TITLE
--tex_notex_libs was assinged incorrectly

### ISSUE THREAD

**Issue by sternp** [Sung-Huan/ANNOgesic#30]
Hi,

I'm trying to execute the command shown below however I keep getting the following error:
```
Error: The --tex_notex_libs was assinged incorrectly. Please check it again.
```

Command:
```
WIG_FOLDER="ANNOgesic/input/wigs/fragment"
LIBS="$WIG_FOLDER/rev2.wig:frag:1:a:- $WIG_FOLDER/fwd2.wig:frag:1:a:+"

#Run TSS
singularity exec -B ANNOgesic annogesic.img \
annogesic \
tss_ps \
--fasta_files MGYG-HGUT-00001.fna \
--annotation_files GUT_GENOME000001.gff \
--project_path ANNOgesic \
--program TSS \
--tex_notex_libs $LIBS \
--condition_names fileName \
--replicate_tex all_1
```

Example wiggle file:
```
head $WIG_FOLDER/rev2.wig

track type=wiggle_0 name=fileName
variableStep chrom=GUT_GENOME000001_1 span=1
34	1
35	1
36	1
37	1
38	1
39	1
40	1
41	1
```

I've been scratching my head about what the issue is. Can you please help?

Thanks!.

**Comment by Sung-Huan** [comment]
Hi,

Your issue is caused by assigning fragmented or conventional RNA-Seq data to tex-notex_libs. Since you are using "fragment", you should assign your wig files to --frag_libs not --tex-notex_libs.

Best,
Sung-Huan

**Comment by sternp** [comment]
```


WIG_FOLDER="ANNOgesic/input/wigs/fragment"
LIBS="$WIG_FOLDER/rev2.wig:notex:1:a:- $WIG_FOLDER/fwd2.wig:notex:1:a:+"

#Run TSS
singularity exec -B /lustre/work-lustre/microbiome/users/sternesp/annogesic/ANNOgesic annogesic.img \
annogesic \
tss_ps \
--fasta_files MGYG-HGUT-00001.fna \
--annotation_files GUT_GENOME000001.gff \
--project_path ANNOgesic \
--program TSS \
--tex_notex_libs $LIBS \
--condition_names fileName \
--replicate_tex all_1
```

`Error: The --tex_notex_libs was assinged incorrectly. Please check it again.`

I still get the same error unfortunately.

**Comment by sternp** [comment]
I should also mention that I'm using the Docker version and that --tex_notex_libs is an essential parameter as there is no --frag_libs option

**Comment by Sung-Huan** [comment]
Sorry, my bad. I didn't notice you are running TSS prediction. For TSS and processing site prediction, dRNA-seq are needed. Thus, the conventional RNA-seq is not acceptable for TSS prediction currently. We are still developing new feature for using conventional RNA-seq to detect TSSs. But you still can use --frag-lib for other predictions. If you want to detect sRNA, you can do so without assigning TSS information.

**Comment by sternp** [comment]
Ah yes. I see now. Thanks for the clarification.

Since I don't have dRNA-seq data, which parts of the analysis can I complete without TSS prediction. I'm interested in array of features such as sRNA, sORF, riboswitches, UTRs, CRISPRs and operons

**Comment by Sung-Huan** [comment]
I think you can do all of them, otherwise, the error message will let you know. But, of course, having TSS information can get more accurate results.
