### ISSUE TITLE
TSSpredator error

### ISSUE THREAD

**Issue by Rexomania1** [Sung-Huan/ANNOgesic#32]
I am having issues with the TSSpredator in the Annogesic pipeline. There seems to be an issue with the configuration file. I experienced this error after updating my version of Annogesic both in singularity and docker. Please find below my error message for your perusal:
Singularity error:
Running TSSpredator for NC_018658.1
Error: There is not MasterTable file in /home/rna-seq/Rex/DFG/new_data/Annogesic_noblast/output/TSSs/MasterTables/MasterTable_NC_018660.1
Please check configuration file.
Error: There is not MasterTable file in /home/rna-seq/Rex/DFG/new_data/Annogesic_noblast/output/TSSs/MasterTables/MasterTable_NC_018659.1
Please check configuration file.
Error: There is not MasterTable file in /home/rna-seq/Rex/DFG/new_data/Annogesic_noblast/output/TSSs/MasterTables/MasterTable_NC_018666.1
Please check configuration file.
Error: There is not MasterTable file in /home/rna-seq/Rex/DFG/new_data/Annogesic_noblast/output/TSSs/MasterTables/MasterTable_NC_018658.1
Please check configuration file.
Merging gff files of GCF_000299455.1_ASM29945v1_genomic_new_TSS
Running statistaics
Validating TSSs with genome annotations
Remove temperary files and folders

Docker error:
Traceback (most recent call last):
  File "/usr/local/bin/annogesic", line 2238, in <module>
    main()
  File "/usr/local/bin/annogesic", line 2154, in main
    args.func(controller)
  File "/usr/local/bin/annogesic", line 2179, in run_TSSpredator
    controller.tsspredator()
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/controller.py", line 329, in tsspredator
    tsspredator.run_tsspredator(args_tss, log)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/tsspredator.py", line 621, in run_tsspredator
    self._convert_gff(prefixs, args_tss, log)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/tsspredator.py", line 338, in _convert_gff
    self.converter.convert_mastertable2gff(
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/converter.py", line 371, in convert_mastertable2gff
    tss_libs = self._get_libs(tss_file)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/converter.py", line 350, in _get_libs
    for tss in self.tssparser.entries(tss_fh):
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/TSSpredator_parser.py", line 10, in entries
    yield TSSPredatorEntry(row)
  File "/usr/local/lib/python3.8/dist-packages/annogesiclib/TSSpredator_parser.py", line 16, in __init__
    assert(len(row) == 30)
AssertionError

This error doesn’t pop up with the older versions of annogesic.  Can you please have a look at this error? Thanks

**Comment by Sung-Huan** [comment]
Hi,

Thank you for your email. Please provide me the following information.

1. Which version is your "old version". We did some modifications for adapting the new version of TSSpredator several months ago. It may be the reason. If you can tell me which version that you used before, it can help us to figure out the issue.
2. Please also provide your input files to me. I can try to run it from my side. And make sure this error is not from the conflict of the new version of TSSpredator.
3. Please compress all files in your output folder of tss prediction. I can check the intermediate files to figure out what happened in your run.

Best,
Sung-Huan

**Comment by Rexomania1** [comment]
The answers to your question are as below:
 1.    I used ANNOgesic version 1.0.11 before upgrading it to the latest version.
2&3. I have sent you the zipped Annogesic analysis folder via WeTransfer for your email
Please don't hesitate to contact me if needs be for further clarification.

**Comment by Sung-Huan** [comment]
Thank you for your information. But I still haven't received your files. Just in case, my email address is silasysh@g-mail.nsysu.edu.tw.

**Comment by Sung-Huan** [comment]
Hi,

From my side, everything is fine. I finish the run via Docker without any errors.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/6706987/177917858-410c32e7-688c-4f8a-8540-3044d7f2d98c.png">

I would suggest you to do the following things.
1. delete the current Docker image and re-download it again. Perhaps, your docker image is not downloaded completely.
2. clean up the files in your working folder like removing all files which are not related to ANNOgesic. Moreover, remove output/TSSs folder. Then re-run tss_ps. Perhaps, there is some unproper filenames cause conflicts.
3. If 1 and 2 still cannot solve the issue, create a completely new folder and create a new analysis folder for ANNOgesic by using "create" of ANNOgesic, then copy the required input files to the input folder of your analysis folder. Re-run tss_ps again. This can make sure your run is completely the same as mine. 

Btw. I got the files from my previous mail account. I left my PostDoc group and start my own group around 1 year ago. Please contact me via my new email account in the future - silasysh@g-mail.nsysu.edu.tw

Best,
Sung-Huan

**Comment by Rexomania1** [comment]
Hi Sung-Huan, 
After deleting the old docker image and pulling a new one, the issues is resolved. I built a new singularity image as well as, and TSSpredator is running smoothly. Thanks your patience and assistance.

**Comment by Rexomania1** [comment]
Hi,

Thank you for your prompt response. The answers to your question are as below:



1.       I used ANNOgesic version 1.0.11 before upgrading it to the latest version today.

2&3. I have sent you the zipped Annogesic analysis folder via WeTransfer for you perusual.

Please don't hesitate to contact me if needs be for further clarification.


Regards,

Rexford
