### ISSUE TITLE
annogesic: error: unrecognized arguments: --tsspredator_jar TSSpredator-1.1beta.jar

### ISSUE THREAD

**Issue by KMS-Rock** [Sung-Huan/ANNOgesic#36]
I am using annogesic for TSS identification and for other purpose, I installed annogesic updated java to 8, installed dependencies. I checked it is executable, i given -t, --tsspredator and even gave full command, I tried almost everything possible, but annogesic is not recognizing jar file. Kindly inform me if you have any sugeesion. I tried with /usr/local/bin/jar.file and also in placing jar file in working directory, but in any case its is not recognizing, I tried a lot but every time annogesic through error that unrecognized jar file. 
Kindly suggest me, I shall be thankful

Thanks

**Comment by Sung-Huan** [comment]
Hi,

Thank you for using ANNOgesic. Regarding your issue, please paste the command that you are using. I can take a look.

Best
Sung-Huan

**Comment by KMS-Rock** [comment]
**annogesic tss_ps -pj ./output -b** 1_merged.bam 2_merged.bam 3_merged.bam 4_merged.bam 5_merged.bam 6_merged.bam 7_merged.bam 8_merged.bam **-g** GCF_000203835.1_ASM20383v1_genomic.gff **-p TSS -f** GCA_000203835.1_ASM20383v1_genomic.fna -**tl** T1_merged.bed T2_merged.bed T3_merged.bed T4_merged.bed T5_merged.bed T6_merged.bed T7_merged.bed T8_merged.bed **-rt** "rep1,rep2,rep3" -cn "18h_treatment1,18h_treatment2,18h_treatment3,18h_treatment4,42h_treatment1,42h_treatment2,42h_treatment3,42h_treatment4" **--cluster 2 --tsspredator TSSpredator-1.1beta.jar**

Sorry a lot input files but I changed command in bold text

**Comment by Sung-Huan** [comment]
Thanks. I think your command is totally not correct. All the parameters are set wrong.

1. In tss_ps, there is no -b. BAM file is not a proper input file for tss_ps.
2. -tl should be assigned as wig format file, not bed file. And the way to assign the input files is also not correct.
3. The way that you assign the -rt is also not correct.
4. -cn is also not correct.

There are many some other errors in your command, but I currently do not see them.

Basically, I would recommend you to read the documentation again carefully. The tutorial and subcommands sections describe how to run ANNOgesic with all details. When you read the documentation, please do not just read the tss section. You should read the first several sections as well. There is information about how to setup and arrange the library.

https://annogesic.readthedocs.io/en/latest/subcommands.html
https://annogesic.readthedocs.io/en/latest/tutorial.html

Best
