### ISSUE TITLE
Use normalized or raw coverage files for ANNOgesic?

### ISSUE THREAD

**Issue by kmuench** [Sung-Huan/ANNOgesic#37]
Hello, 

I prepared my .wig/coverage files using READemption2 (multi-species). I see that the tutorial recommends using the coverage files in the READemption subdir READemption_analysis/output/coverage. As referenced in the tutorial, there is no single coverage dir, but multiple dirs - one for each species for the raw data (e.g. species1_coverage-raw, species2_coverage-raw), and then some for normalized data (e.g. species1_coverage-tnoar_mil_normalized and species1_coverage-tnoar_min_normalized).

Does READemption perform better with raw coverage data? Or is it important to use normalized data?

Thank you very much!

**Comment by Sung-Huan** [comment]
Hi.

Thank you for the question. Actually, we tried all of them and similar results were shown. So, based on my experiences, no obvious differences between these libs. Yet, based on the statistics aspect, coverage-tnoar_min_normalized makes more sense. This coverage data is normalized by the total number of aligned reads (TNOAR) of the individual library and then multiplied by the lowest TNOAR value of all libraries. But if your sequence depth is not deep, you can try the raw one or coverage-tnoar_mil_normalized one, or play around some parameters such as --height of transcript detection.

Best,
Sung-Huan
