### ISSUE TITLE
Wig file creation and normalization

### ISSUE THREAD

**Issue by apredeus** [Sung-Huan/ANNOgesic#4]
Hello Sung-Huan, 

I've ran into the following issue when trying to run ANNOgesic on my own data (tutorial worked OK). I'm trying to predict TSS using dRNAseq and RNAseq under same conditions. 

However, I've made my wig files from bigWig, that was in turn made from a bedGraph. Furthermore, I have applied a certain normalization, so that libraries ran to a different scale would look comparable: 

```bash
BPS=`samtools view $TAG.bam | cut -f 6 | perl -ne 'm/(\d+)M/; print "$1\n";' | awk '{sum+=$1} END {print sum}'`
SCF=`echo $BPS | awk '{printf "%.3f\n",1000000000/$1}'`
bedtools genomecov -scale  $SCF -ibam $TAG.bam -bg -strand + > $TAG.plus.bedGraph
bedtools genomecov -scale -$SCF -ibam $TAG.bam -bg -strand - > $TAG.minus.bedGraph

bedGraphToBigWig $TAG.plus.bedGraph  $CHROM $TAG.plus.bw
bedGraphToBigWig $TAG.minus.bedGraph $CHROM $TAG.minus.bw
```

However, when I convert the obtained bw to wig, it looks different, and makes wig file parser from TSS predator fail: 

> ==> A1636-dRNA-Pool-BPS_S37.minus.wig <==
> #bedGraph section A1636_v1_chr:0-10009
> A1636_v1_chr	0	42	-0.937
> A1636_v1_chr	42	43	-1.874
> A1636_v1_chr	43	46	-2.811

Here's the output from TSS prediction run: 

> Running TSS prediction
> Checking gff file of A1636_v1_2018.gff
> Warning: Repeat locus_tag A1636_02668 in gff file!!!
> Parsing A1636_v1_2018.fa
> Parsing A1636_v1_2018.gff
> Parsing A1636-dRNA-Pool-BPS_S37.minus.wig
> Traceback (most recent call last):
>   File "/usr/local/bin/annogesic", line 2180, in <module>
>     main()
>   File "/usr/local/bin/annogesic", line 2096, in main
>     args.func(controller)
>   File "/usr/local/bin/annogesic", line 2121, in run_TSSpredator
>     controller.tsspredator()
>   File "/usr/local/lib/python3.5/dist-packages/annogesiclib/controller.py", line 327, in tsspredator
>     tsspredator.run_tsspredator(args_tss, log)
>   File "/usr/local/lib/python3.5/dist-packages/annogesiclib/tsspredator.py", line 491, in run_tsspredator
>     self.multiparser.parser_wig(args_tss.wig_folder)
>   File "/usr/local/lib/python3.5/dist-packages/annogesiclib/multiparser.py", line 359, in parser_wig
>     out.write(" ".join(line))
> AttributeError: 'NoneType' object has no attribute 'write'

I would appreciate any suggestions about how to fix this. Do I need to re-make my wig files? Thank you!

**Comment by Sung-Huan** [comment]
Dear Alex,

I guess the header of your new wig files have something different. The header of the normal wig file is:

track type=wiggle_0 name=$FILENAME
variableStep chrom=$STRAIN span=1

Could you please check it?

Best,
Sung-Huan

**Comment by apredeus** [comment]
Yes, I see that my way of getting wig files does not generate a proper wig header. Strange! 

How do you generate wig files from the alignments? Are they scaled in any way, before you are using them in the TSS prediction pipeline? 

Thanks again.

**Comment by Sung-Huan** [comment]
Of course, if the number of wiggle files is not too many, you can also add the header manually. Just need to follow the format correctly.

track type=wiggle_0 name="label name"
variableStep chrom="strain name" span=1

The "label name" can be replaced, but "label name" of the wiggle files from the same condition should be the same (ex: forward and reverse strand). And the "strain name" can be replaced by your strain.

**Comment by apredeus** [comment]
Thank you. I'm using my own pipeline for multi-strain processing, so I didn't want to re-process the data. I've found a custom solution to generate an appropriately formatted wig, and everything worked! 

One question I that remains: do you have any idea if wig files generated by READemption are normalized (scaled), and if so, how important is it for the proper functioning of the predictor?

**Comment by Sung-Huan** [comment]
Yes, READemption provides normalized one as well. We also tested both of the raw coverage files and normalized coverage files. The results show similar. Of course, some of our collaborator think that using raw files may make more sense because the cutoff of minimum coverage is easier to manage.

**Comment by apredeus** [comment]
Thank you, this helps. I would imagine using normalized wig files is definitely needed when comparing depths of dRNAseq/RNAseq and selecting peaks manually.
