### ISSUE TITLE
Missing file error where it is generated temprory by the pipeline in sRNA detection subcommand

### ISSUE THREAD

**Issue by elhossary** [Sung-Huan/ANNOgesic#7]
Missing file error where it is generated temprory by the pipeline 
The file is accutally there but in a step back directory.

![Annotation 2019-06-23 184749](https://user-images.githubusercontent.com/12513051/60032635-4a31e700-96a7-11e9-84fa-49922b125f86.png)

**Comment by Sung-Huan** [comment]
The bug is fixed in 1.0.3.

**Comment by elhossary** [comment]
fixed
