### ISSUE TITLE
ERROR: int is not iterable, in promoter prediction subcommand

### ISSUE THREAD

**Issue by elhossary** [Sung-Huan/ANNOgesic#8]
ERROR: int is not iterable, in promoter prediction subcommand

![Annotation 2019-06-23 144001](https://user-images.githubusercontent.com/12513051/60032874-c4fb0200-96a7-11e9-9cf1-eeaeb59fd02d.png)

**Comment by Sung-Huan** [comment]
The error is from the default setting. I fixed the bug in 1.0.3.

**Comment by elhossary** [comment]
thanks for fixing
