### ISSUE TITLE
sRNA prediction from RNA-seq data

### ISSUE THREAD

**Issue by StephenLi55** [Sung-Huan/ANNOgesic#9]
Hi Sung-Huan,

  I am looking into the possibility of performing sRNA prediction from my RNA-seq data. Currently my data are in fastq and Bam formats, which seems to be different from the required input file format for the sRNA detection mode. 

  From what I have read so far, it seems like I will have to convert my Bam files into Wig files, which then can became the input file for generating a transcript file using the transcript detection mode. The transcript file then can be an input for the sRNA detection mode. However, I am not sure if thats the right way to go.  Or am I over-complicating things ? Are there other ways to perform sRNA detection with ANNOgesic using either fastq file or Bam files?

  thanks a lot in advance,

  Stephen

**Comment by Sung-Huan** [comment]
Dear Stephen,

Wig format is the right format for the sRNA detection. There are many tools or scripts that can convert BAM to wig files, like:

https://metacpan.org/pod/distribution/Bio-ToolBox/scripts/bam2wig.pl
https://reademption.readthedocs.io/en/latest/subcommands.html#coverage

Best,

Sung-Huan
